# Generated by Django 4.2.2 on 2023-07-04 05:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("auctions", "0006_bid_created_at_bid_updated_at_category_created_at_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="category",
            field=models.CharField(max_length=64, unique=True),
        ),
    ]
