# Generated by Django 4.2.2 on 2023-07-05 05:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("auctions", "0007_alter_category_category"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="listing",
            name="watchlist",
        ),
        migrations.AddField(
            model_name="bid",
            name="winner",
            field=models.BooleanField(default=False),
        ),
    ]
