# Generated by Django 4.2.2 on 2023-07-08 17:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("auctions", "0008_remove_listing_watchlist_bid_winner"),
    ]

    operations = [
        migrations.AlterField(
            model_name="listing",
            name="description",
            field=models.TextField(),
        ),
    ]
